name: Deploy with doppler and pulumi
description: Builds a docker image and deploys
inputs:
  environment:
    description: 'Environment that the deployment is in'
    required: true
  file:
    description: 'Path to dockerfile to build'
    required: true
  tag:
    description: 'Docker image tag'
    required: true
  app_name:
    description: 'App to be deployed'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  aws_access_key_id:
    description: 'AWS access key id'
    required: true
  aws_access_key:
    description: 'AWS access key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build
      uses: ./build-cached
      with:
        file: ${{ inputs.file }}
        tags: ${{ inputs.tag }}
        target: release
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
    - name: Install Pulumi and infra tools
      shell: bash
      run: cd infrastructure && bun install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-region: ${{ inputs.aws_region }}
        aws-secret-access-key: ${{ inputs.aws_access_key }}
    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: ${{ inputs.environment }}
        work-dir: infrastructure/${{ inputs.app_name }}
        refresh: true
        upsert: true