name: Deploy with doppler and pulumi
description: Builds a docker image and deploys
inputs:
  environment:
    description: 'Environment that the deployment is in'
    required: true
  file:
    description: 'Path to dockerfile to build'
    required: true
  tag:
    description: 'Docker image tag'
    required: true
  app_name:
    description: 'App to be deployed'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build
      uses: simon-norman/actions/build-cached@main
      with:
        file: ${{ inputs.file }}
        tags: ${{ inputs.tag }}
        target: release
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ inputs.aws_region }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: ${{ inputs.environment }}
        work-dir: infrastructure/${{app_name}}
        refresh: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}