name: Update major version with latest tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-major-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update major
        uses: ./point-major-to-latest-tag