on:
  release:
    types:
      - released
      - edited
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - '**'
    paths-ignore:
      - '**'
      
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create / update latest major tag
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true