name: Keep the versions up-to-date

on:
  release:
    types:
      - released
      - published
      - edited

jobs:
  actions-tagger:
    runs-on: windows-latest
    permissions: # (2)
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true